# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de4baf1bf76501e9b88b8f9525066d6d5613f546856191f0f534da7dba6094e7d6af069c387aba42641a0b6fb0ff45f5aa367a97febc461ec8733931434eb77d

test:
  secret_key_base: 5ce8a80c41cb57b43d05e6952cedd42abec7d68424570ec8595400c3b1ed866d3c026fd6e687640f82275875564dc4e20e73b9a28289da54d926848e1285d33d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
